In [1]:
import numpy as np

In [2]:
mylist = np.array([[1,2],[3,1]])

In [3]:
my_list = [i for i in range(10)]
type(my_list)

list

In [5]:
my_list*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
myarray = np.array(my_list)
type(myarray)

numpy.ndarray

In [8]:
myarray**.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
mymatrix = np.array([[0,1,5],[-2,1,4],[7,8,9]])
mymatrix

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

In [10]:
mymatrix[:,0:1]

array([[ 0],
       [-2],
       [ 7]])

In [11]:
mymatrix[:,1:2]

array([[1],
       [1],
       [8]])

In [12]:
mymatrix[0:3,1:2]

array([[1],
       [1],
       [8]])

In [13]:
mymatrix[:,2:3]

array([[5],
       [4],
       [9]])

In [14]:
mymatrix[:,0:3]

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

In [15]:
mymatrix[:,:]

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

In [16]:
myarange = np.arange(10)
myarange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
myrangestep = np.arange(0,10,2)
myrangestep

array([0, 2, 4, 6, 8])

In [18]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [20]:
Z0 = np.zeros((3,3))
Z0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
O1 = np.ones(5)
O1

array([1., 1., 1., 1., 1.])

In [23]:
O6 = np.ones((6,6))
O6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
L = np.linspace(1,25,9)
L

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [37]:
L3 = L.reshape(3,3)
L3

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

In [39]:
I2 = np.eye(2)
I2

array([[1., 0.],
       [0., 1.]])

In [41]:
I2 = np.eye(2,4)
I2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [43]:
I2[0:2,0:2]


array([[1., 0.],
       [0., 1.]])

In [44]:
import random 

In [46]:
arr = np.random.rand(3,4)
arr

array([[0.98924207, 0.80910629, 0.18070623, 0.58201233],
       [0.15205165, 0.25221965, 0.53070677, 0.41373276],
       [0.72845393, 0.73257058, 0.60122032, 0.67835596]])

In [47]:
from numpy.random import rand

In [48]:
arr_simple = rand(3,4)
arr_simple

array([[0.75177577, 0.68373175, 0.35913518, 0.14693541],
       [0.94867169, 0.29471601, 0.32782296, 0.58642046],
       [0.03430618, 0.23874315, 0.16479904, 0.42082964]])

In [49]:
from numpy.random import randn

In [50]:
mat = randn(3,2)
mat

array([[ 0.05906296,  2.06947037],
       [ 0.11293833, -2.39022865],
       [ 0.18040691, -1.15720085]])

In [55]:
l = lambda x: x**2
l(5)

25

In [56]:
l = lambda x: x.split('@')
l('mdoumbia@howard.edu')

['mdoumbia', 'howard.edu']